apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: samplecatalina/orders
          env:
            # Kafka client ID using pod metadata name
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # Kafka brokers, replace with actual broker addresses
            - name: KAFKA_BROKERS
              value: 'kafka-srv:9092'
            # MongoDB connection string
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders' # /orders if to define the DB/table name
            # JWT secret key from Kubernetes secret
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      port: 3000
      targetPort: 3000
