apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: samplecatalina/tickets
          env:
            # Kafka client ID using pod metadata name
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # Kafka brokers, replace with actual broker addresses
            - name: KAFKA_BROKERS
              value: 'kafka-srv:9092'
            # MongoDB connection string for the tickets service
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets' # /tickets if to define the DB/table name
            # JWT secret key from Kubernetes secret
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      port: 3000
      targetPort: 3000
