name: tests-tickets

on:
  pull_request:
    paths:
      - 'services/tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/tickets && npm i && npm run test:ci
