name: tests-auth

on:
  pull_request:
    paths:
      - 'services/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/auth && npm i && npm run test:ci
